language: node_js
node_js:
- stable
install:
- npm ci
cache:
  directories:
  - "$/.npm"
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: kcnC/oRqmk0lUuPVZyHn6waUV++69aZ4Vaj9uxhQquXv0RFN+Yji90rRtfKtblyjEkIUuLAVY2x2qf0RnhfSJTlraz9g+WSERfndcprv9rlwwzqpbwc8zHd93qk1GWi23IOzzpY8JWc0T9IKcjzLeN7Gu0H/YvPxC02IAbQvXdLiy/VjZaSHAwUv1Zqok4/KY+E+9hyYv/utaBn0FdB3eYiO+8gq2abrccLRAozSv0TX7RUCyw7TSIx0Rf7BlJGislIVL/dgefMJRxfgKPrS4Qd8Wo+f3Zb8qMUJ0WviYj14Ny8gtD9SQOny4Ix17b0Me9vOZtY5iL7tZ+i9IDmmWy56Lsv2kjsFZocoMdkXKPo9vSbhtEXK4iwGfhcLJ0IJaVwa5WIUWZz1EUSCK2wNBs8t8jDxZX7v2KFST52NU+C5xjR/CrEIjvjR/YfrqpMnjXfYA7Z3zU/N13imv9AOCXqxLqgBvWDRnnYModnoQKP8b+x4mHb5vDSbCl0cHKl7Bc6g/oul5YSvUG5CwlzuruJVEN9DoUvxW2ThLU3Xhhq0k/kl1eLiSJg4ePMuo+JXrB96tU8HuUMJRt4RIMjQm21PphSWaURS8bGtoEJnQwZ9LAnow/04xXKzHaDCmBLernhEgBkCMfEa7HKfEBOeF02/uLxdhbi73Xyipf5/PEY=
  app: this-quantified-backend
  on:
    repo: Myrdden/quantified-backend
