language: node_js
node_js:
  - "stable"
install:
  - npm ci
cache:
  directories:
    - "$/.npm"
deploy:
  provider: heroku
  api_key:
    secure: bEdBLPDuZW7wnVTSphz/PQXC90omkSSGETwxda1SrK9c1bG6Xhh52R1pmd7KkytTMTkFDOdZz/ywza4ojMp9TTOyZRbLNoSJU2l5TWMRwTsNUXuuwBmIrGpXx8p1DtpcZgsgdiiBopd86IcUd7YYCff9gFTPurgt3iWVI1oVbEiHk3SvragZu3K5bqvXqb4YBAMQJ9SXYpyau52B1aB3YxwQ6n1ilAQMYkIDUbUleSLhGsGZqqln+4J6rTj+gsX+0GHHI1toJQDNs90kgGHy8un4yiHJFs753H8fyvatlme4ie/eKDFiXo/8XqFzntBLfNI6RcrgBUtpwAc4wM/bF5XNdjup2lP5keLODzuDF5TQ6hX8n+Dc2DjF99nFFAClxgPo/boZMHad0An7zF8NKD/vnwL4gi5x5vlIONCsAlaqjgxDMbwgwEmB6/wC1+oyk5sNfIE3Esm8mh4O6EMS2iWzwgf/kEb0ZS15IEw/p4Ik90aq2pjHvqXymmsgXsPvYnXGhVanvHQ/PBZvjSoE3DeD0YxQ1MtjMvPTuEEOED+LXZx3Ej0CcF8R+bz4jw0h3uFvVcNH95sP3TYLczMKR4xFFx33vwzUSNW1PUnvjeklF7XSDpRXceHZjMurrWixVaihW/gcD0iAf205vqYROZ4yklDuTTVAevWYSZqWmrQ=
  app: this-quantified-backend
  on:
    repo: Myrdden/quantified-backend

